# Generated by Django 5.0.2 on 2024-02-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_a_pregunta_opcion_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='explicacion',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
